### ISSUE TITLE
Invalid Date is not caught

### ISSUE THREAD

**Issue by jhoch** [ianstormtaylor/superstruct#115]
Input:

```
const { superstruct, struct } = window.Superstruct

const User = struct({
  id: 'number',
  date: 'date',
})

const data = {
  id: 1,
  date: new Date('Jane Smith'),
}

try {
  const user = User(data)
  log('valid', user)
} catch (e) {
  const { message, path, data, type, value } = e
  log('invalid', { message, path, data, type, value })
}

function log(type, data) {
  document.body.className = type
  document.body.textContent = JSON.stringify(data, null, 2)
}
```

Actual Output:
```
{
  "id": 1,
  "date": null
}
```

Expected Output: Something like...
```
{
  "message": "Invalid date for `date`.",
  "path": [
    "date"
  ],
  "data": {
    "id": 1,
    "date": "Date(\"Invalid Date\")"
  },
  "type": "date",
  "value": "Date(\"Invalid Date\")"
}
```

**Comment by ianstormtaylor** [comment]
Hey @jhoch! Good catch here. 

I was kind of unsure, since it's still an instance of `Date`, so it felt weird to exclude it, but I just did some digging and apparently calling `toISOString` on and invalid `Date` will throw an error, which definitely could lead to some strange bugs, and `toJSON` will return `null`. So it does seem like having this extra check in core would make sense to prevent those weird cases. I'll add a fix!
