### ISSUE TITLE
What does a required value mean?

### ISSUE THREAD

**Issue by thany** [ianstormtaylor/superstruct#1264]
I get it. Technically speaking this makes a string required:

```typescript
object({
  firstName: string(),
});
```

But not actually, when used together with form values. Any form value that is *not* filled in, will be an empty string, which validates the above example perfectly fine. Again, *technically* this is correct, but *practically* it's not what I would expect.

To fix this, I have to go:

```typescript
object({
  firstName: size(string(), 1, Infinity),
});
```

This has three big disadvantages:

1. It's hard to read. Anyone seeing this for the first will be like "mate, what the hell is that?" and I'd have to explain it every time.
2. It becomes quite convoluted quite quickly for a form with many fields, all of which are required and may have additional validation rules, like patterns.
3. In terms of validation messages, it's not so easy anymore to differentiate between a required string, and a string that has a *meaningful* minimum length. One has to say "this field is required" and the other "please use a minimum of N characters". I imagine this will be convoluted at best to set up.

The only advantage is that the validation that occurs is *technically* correct, which is of course very useful for validating data that is passed around through an API or whatever.

So how about we make it possible to specify what it means exactly, for a value to be required/optional.

Or perhaps I'm using totally the wrong package for my use case (form validation)? But I do have to say react-hook-forms (which is what I use) does support superstruct natively, so it ought to be usable with forms, iyam.

**Comment by arturmuller** [comment]
Hey @thany -- what you might be looking for is the `nonempty()` refinement ([docs]()https://docs.superstructjs.org/api-reference/refinements#nonempty)

In your case, you could use it like so: 

```ts
object({
  firstName: nonempty(string()),
});
```

Structs are just values, so you could also do something like:

```ts
object({

  firstName: requiredString,
});
```

**Comment by arturmuller** [comment]
I personally use Superstruct for form validation so it can 100% be used that way, but whether or not it is the right choice for you depends probably on how strict you want to be about your validation and the rest of your stack.

I like when my validation library is very strict so that I am 100% sure about my data and I know no magic is happening behind the scenes. It's also great that superstruct can be used for a variety of use-cases: using a single validation lib across the stack works for me, as I like that I don't have to use multiple slightly different APIs in different places.

However, other libs, like Yup, are a bit more focused specifically on form validation, which makes them perhaps a bit more terse, which might be preferred in some cases.
