### ISSUE TITLE
add schema builder

### ISSUE THREAD

**Issue by seeden** [ianstormtaylor/superstruct#26]
Hi @ianstormtaylor 

I really like your library because I have used ajv and joi as well and I was frustrated from these libraries. 
I would like to use your library with abstraction layer because I do not want to write types as string Because I will write typos like 'string' 'String' and others variants :) 

I saw very nice abstraction on the top of ajv.
https://github.com/RomAnoX/ajv-schema-builder

What do you think about this idea?
Thank you

**Comment by ianstormtaylor** [comment]
Hey @seeden, glad you like it!

For what it's worth, the library will actually throw if a type isn't recognized when compiling, so if you write `'String'` instead of `'string'` it will throw an error and you'll immediately know there was a mistake. So I'm not sure you'd gain _that_ much from a fluent API.

I actually made it strings on purpose because it allows the schemas to be a lot terser, which I found makes me more likely to use them, and makes it easier to standardize what the "custom" data types are in a single place.

That said, if you really want a fluent API, and are down with "models", check out [`tcomb`](https://github.com/gcanti/tcomb), it might be something you like!

Feel free to follow up with more questions if you'd like too.
