### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by igordonin** [ianstormtaylor/superstruct#39]
When the data passed in has multiple validation errors, superstruct will throw upon the first error. I think it would be very much desirable to collect all errors and return them. That would make it much more useful, specially for large complex types with many fields.

**Comment by ianstormtaylor** [comment]
Hey @igordonin, good question.

The first error is indeed the one that is thrown, although there is an `error.errors` property that contains a list of all of the errors that occurred. I designed it this way so that for the simpler cases people can deal with single thrown errors, but for the more complex cases people can dig in and get more information.

Multiple errors are processed in layers. Such that for a struct like:

```js
const User = struct({
  id: 'number',
  name: 'string',
})
```

If you pass in `'invalid'`, you won't receive errors for each of the properties, because the entire value didn't pass the first layer of validation that validates it is an object. Once it is an object, you'll receive multiple errors for each of the properties if any are invalid. Hope that makes sense.

I've just updated the documentation to hopefully make this a bit easier to find. Thank you!
