### ISSUE TITLE
Coercion runs validation, and returns empty `path` and incorrect `branch`?

### ISSUE THREAD

**Issue by rossholdway** [ianstormtaylor/superstruct#395]
Hi, I really like the concept / idea behind superstruct (thank you for making it!) but am finding it difficult to fully understand how to use coercion.

I was not expecting the `coerce` method to also validate the object by calling `assert` for me internally.

https://github.com/ianstormtaylor/superstruct/blob/0206f36a9b85542a1e7ab4d9653db5b72f04e3db/src/struct.ts#L138-L142

My real issue is that if the validation fails during coercion (as it does below ('secret' is < 8 characters)), in `StructError` the path is empty, and the `branch` is missing the initial value? Is this a bug or expected?

```typescript
let i = 0;
const password = refinement(string(), 'password', value => {
  return value.length > 8;
});

const User = object({
  id: defaulted(number(), () => ++i),
  name: string(),
  password: password
});
type User = StructType<typeof User>;

function validate(name: string, password: string): [StructError, undefined] | [undefined, User] {
  try {
    return [undefined, coerce({
      name: name,
      password,
    }, User)];
  } catch(error) {
    return [error, undefined];
  }
}

console.log(validate('Ross', 'secret'));

// Output
// ...
// value: 'secret',
// type: 'password',
// path: [],
// branch: [ 'secret' ],
// ...
```

(Also, while I'm on the subject of coercion I though't I'd point out that the variable name `PositiveInteger` in the documentation for "Custom Coercions" is confusing. I guess it was just missed during a refactor! https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#custom-coercions

**Comment by yalon** [comment]
Hi, just wanted to express my gratitude for a package nicely done! I'm piggybacking on this issue with (hopefully) a relevant comment. 

I use this to validate types that come from a remote server, and one behavior that I found is that sometimes an API will omit a key entirely instead of returning a null value.
While I understand that this gets handled with coerce and optional(), I would like to suggest two things:
1. Coerce should return an [error, object] just like the other API and not throw an exception. This would clean the call site code and not make me afraid of uncaught exceptions running around raising havoc, especially if they're part of async code.
2. With typescript at least, the default value is set to any, which makes it very easy to put something there that coerce won't like at runtime and then throw a very non-user-friendly error, for example:

```
export const MessagesListResponseT = S.object({
    messages: S.defaulted(S.array(S.string()), () => []),
    nextPageToken: S.defaulted(S.string(), null),
    resultSizeEstimate: S.defaulted(S.number(), null)
});

> let oo = { resultSizeEstimate: 0 };
> S.coerce(oo, MessagesListResponseT);
/Users/acme/git/blat/node_modules/superstruct/lib/index.cjs:170
    throw result[0];
    ^

Uncaught Error:
    at new StructError (/Users/acme/git/blat/node_modules/superstruct/src/struct.ts:71:18)
    at validate (/Users/acme/git/blat/node_modules/superstruct/src/struct.ts:170:19)
    at assert (/Users/acme/git/blat/node_modules/superstruct/src/struct.ts:127:18)
    at coerce (/Users/acme/git/blat/node_modules/superstruct/src/struct.ts:140:3)
    at Struct.coercer (/Users/acme/git/blat/node_modules/superstruct/src/types.ts:651:18)
    at Object.coerce (/Users/acme/git/blat/node_modules/superstruct/src/struct.ts:139:22)
    at /Users/acme/git/blat/[eval].ts:1:3
    at Script.runInThisContext (vm.js:131:18)
    at exec (/Users/acme/git/blat/node_modules/ts-node/src/bin.ts:347:17)
    at /Users/acme/git/blat/node_modules/ts-node/src/bin.ts:337:27 {
  value: null,
  type: 'string',
  path: [],
  branch: [ null ],
  failures: [GeneratorFunction: failures]
```

After playing with it I realised that this isn't what coerce expects and changed S.defaulted to S.optional and everything was happy again (and I received undefined values for the "missing" keys which I'm quite fine with).

Again, kudos for making this library.

**Comment by thehappybug** [comment]
I started playing with superstruct and ran into the same issue. Coerce error has an empty `path` and incorrect `branch`. It looks like a bug. I am not familiar enough with superstruct's codebase to find where the issue happens.

**Comment by michael-vdvelden-plt** [comment]
Is there any progress on why this is occurring?

**Comment by ianstormtaylor** [comment]
Hey all, coercion has been fixed in the latest version so hopefully this is fixed now. I'm not sure about the path/branch bits, but if it's still happening can you open a new issue with the specific path/branch information that's going missing? Thanks!
