### ISSUE TITLE
$ref another schema

### ISSUE THREAD

**Issue by roccomuso** [ianstormtaylor/superstruct#44]
I wasn't able to find in the doc a clear reference example.
Like the `jsonschema` feature: `$ref: '#ext' // references another schema`

What's the equivalent in superstruct?

**Comment by ianstormtaylor** [comment]
Hey @roccomuso, good question. You can do that by passing in a `Struct` as one of the properties of another one, instead of using a type string. For example:

```js
const User = struct({
  id: 'number',
  name: 'string',
})

const Article = struct({
  id: 'number',
  title: 'string',
  author: User,
})
```

(Anywhere that you can use a `'number'` style string to represent a schema, you can pass a full-fledged `Struct` in too.)

Hope that helps! I'll add a section about this to the docs right now.

**Comment by roccomuso** [comment]
@ianstormtaylor yeah that's one of the most common usage scenario. Thanks.
