### ISSUE TITLE
How to add custom property to struct?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ianstormtaylor/superstruct#444]
I'm thinking to build a form generator. I would like to allow user to add extra metadata on struct, so the generator can read these from the struct instance.

Any idea how to extends the base struct?

**Comment by dhawal1248** [comment]
Hey @xiaoyu-tamu, did you get anything on this?

**Comment by xionluhnis** [comment]
Did #383 actually provide any means to encode metadata in `Struct`?

I was looking for a similar functionality as described in this issue, which my understanding translates into something similar to the [`meta`](https://github.com/jquense/yup#schemametametadata-object-schema) method in yup.

Am I correct that this was not closed because it was implemented, but instead you don't plan on having such capability?
