### ISSUE TITLE
Swap arguments order and add currying for validation functions?

### ISSUE THREAD

**Issue by vaderkos** [ianstormtaylor/superstruct#461]
It would be great if validation functions like _is_, _assert_, _coerce_, _validate_ supported **currying** and had swapped arguments order.

In that way there would a bit more ways to use **superstruct**, so bound function can be easily prepared.

```
import { assert, number, string, StructType } from 'superstruct'

export const ArticleStruct = object({
  id: number(),
  title: string()
})

export type Article = StructType<typeof ArticleStruct>

export const assertArticle = assert(ArticleStruct)

```

**Comment by mikestopcontinues** [comment]
I like this. In the meantime, you can use the babel implementation of the partial operator to get what you want without wrapper functions.

**Comment by ianstormtaylor** [comment]
I need to document this better, but you can already use:

```ts
ArticleStruct.assert(data)
```

Instead of:

```ts
assert(data, ArticleStruct)
```

I'm not sure we gain much more with currying? 

The reason to have the helpers as functional ones at all is unfortunately because we're pushing the limits of what TypeScript is capable of, and TypeScript will error when using `Struct.assert(data)`, which I'm fairly sure will also error when using the curried method. (Here's the TypeScript issue tracking the limitation: https://github.com/microsoft/TypeScript/issues/34596)

**Comment by ianstormtaylor** [comment]
I take it back, I do see the value in offering currying. Once that upstream TypeScript issue is fixed I'm down to have a breaking change to swap the order of those arguments and add currying. I don't want to do it until then though because I don't want to end up with more parts of the codebase that only work when not using TypeScript.

**Comment by arturmuller** [comment]
It seems like the TS issue is not going to be solved. Closing for now.
