### ISSUE TITLE
Record with a required key

### ISSUE THREAD

**Issue by Mrtenz** [ianstormtaylor/superstruct#480]
Is it possible to create a record (e.g. `Record<string, Struct>`) which has one required key? I'm trying to get the equivalent of something like the this in TypeScript:

```ts
interface Type {
  foo: Struct;
  [key: string]: Struct;
}
```

I tried using an `union` with `object` and `record`, but that results in something like

```ts
type Type = { foo: Struct; } | Record<string, Struct>;
```

Which results in "type 'string' can't be used to index type"-like errors elsewhere. I currently solved it by using `refinement` and specifying a custom type as generic parameter, but I'd like to know if there's an easier solution to accomplish this.

**Comment by lynxtaa** [comment]
@Mrtenz Maybe [type](https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#type) will help?

**Comment by Mrtenz** [comment]
I don't think `type` will check any unspecified properties, so I would end up with some kind of custom type validation regardless.

**Comment by ianstormtaylor** [comment]
@Mrtenz check out the `intersection` struct, that is likely what you're after.

**Comment by Mrtenz** [comment]
I don't think that's what I'm looking for. My data looks something like this:

```json
{
  "someRequiredKey": ["..."],
  "someOtherKey": ["..."],
  "...": ["..."]
}
```

Where `someRequiredKey` is required, and the other keys can be arbitrary strings. I tried something like this:

```js
record(
  intersection(
    string(),
    literal('someRequiredKey')
  ),
  array()
)
```

But that doesn't work with `someOtherKey`. My current solution looks like this:

```js
refinement(
  record(
    string(),
    array(EIP_712_TYPE)
  ),
  '...',
  (value) => {
    return !!value.someRequiredKey;
  }
);
```

But then the resulting record isn't fully type safe when using `StructType`. It would be nice if there was a better solution for this.

**Comment by ianstormtaylor** [comment]
My guess is that you're looking for something like:

```ts
const MyArray = array(...)

const MyObject = intersection([
  object({ requiredKey: MyArray }),
  record(string(), MyArray)
])
```

**Comment by Mrtenz** [comment]
That seems to work great, thanks!

**Comment by mellanslag-de** [comment]
I had a similar issue like yours and came up with an I think more elegant solution.
Only downside: You need to define every key that is allowed, wildcards are not possible with this approach as far as I can tell.

The Problem: I want to build an object struct, that has many keys, some have value type A, some have value type B.

The object to validate looks like this:
```ts
{
    key1: "value-A",
    key2: "value-A",
    key3: "value-B",
    key4: "value-B",
    // ... and many more keys of either type A or B 
}
```

Ideally, I'd just define two objects with `record()` and merge them together with `assign()`, like this:
```ts
assign(
    record(union([literal('key1'), literal('key2')]), StructA),
    record(union([literal('key3'), literal('key4')]), StructB),
);
```

But unfortunately, `assign()` only works with objects created with `object()`, not with `record()`.
But with `object()`, it would be a lot more verbose, and I'd have to repeat the value for every key again. And I dont even need `assign()` at all, because I can just define everything within one `object()`.

It would look something like this:
```ts
object({
    key1: StructA,
    key2: StructA,
    key3: StructB,
    key4: StructB,
})
```

**So I created my own little superstruct utility `mappedObject()` that creates an object struct that looks like it was created by `object()`, but actually uses a syntax similar to `record()`:**

```ts
/**
* Utility type for superstruct to generate an object type.
* It uses the syntax of superstruct's record(), but builds a type like object().
* This is necessary if one wants to later use it within assign(), as that is only compatible with object(), not record().
* 
* @param keys - Array of the string object keys of the desired object schema
* @param value - Value of each of the given object keys
* @returns Superstruct object({...}) schema created by the given keys and value struct
*
* @link https://github.com/ianstormtaylor/superstruct/issues/480#issuecomment-2943374720
*/
export function mappedObject<const KEY extends string, VALUE, _OBJ_SCHEMA extends { [key in KEY]: Struct<VALUE> } = { [key in KEY]: Struct<VALUE> }>(
  keys: ReadonlyArray<KEY>,
  value: Struct<VALUE>,
): Struct<ObjectType<_OBJ_SCHEMA>, _OBJ_SCHEMA> {
  return object(Object.fromEntries(keys.map((key) => [key, value]))) as unknown as Struct<ObjectType<_OBJ_SCHEMA>, _OBJ_SCHEMA>;
}
```
(updated typing so that `mappedObject()` also works with superstructs `partial()` utility)

**Usage:**
```ts
const StructA = literal("value-A");
const StructB = literal("value-B");
const MyStruct = assign(mappedObject(["key1", "key2"], StructA), mappedObject(["key3", "key4"], StructB));

const myObj: Infer<typeof MyStruct> = {
    key1: "value-A",
    key2: "value-A",
    key3: "value-B",
    key4: "value-B"
};

is(myObj, MyStruct); // returns true
 
```

Note that with `mappedObject()` (instead of `record()`), you define the keys as an array, not a superstruct `Struct` (eg. `['key1', 'key2', ...]` instead of `union([literal('key1'), literal('key2')])`.
