### ISSUE TITLE
Create Superstruct schema from a Typescript type

### ISSUE THREAD

**Issue by nwaughachukwuma** [ianstormtaylor/superstruct#526]
@ianstormtaylor, the snippet below was gotten from the documentation and shows how to get the Typescript type of a schema. If I wanted to do the reverse, i.e. create a superstruct schema from a Typescript type, how would I go about it?

```ts
const User = object({
  id: number(),
  name: string(),
})

type User = StructType<typeof User>
// type User = {
//   id: number
//   name: string
// }
```

**Comment by thesunny** [comment]
Hi @nwaughachukwuma 

I'm (obviously) not Ian but I contributed some of the docs around TypeScript.

Unfortunately, there is no easy way (that I can see of) to do this programmatically. You can do this by plugging into the TypeScript parser but this is most likely more work than you want to do. The reason why it's difficult to do the reverse is because the TypeScript types aren't accessible to the JavaScript code.

One way you might want to work around this is to tie struct creation into the code that you used to define `User` in the first place.

**Comment by nwaughachukwuma** [comment]
> One way you might want to work around this is to tie struct creation into the code that you used to define `User` in the first place.

Hi @thesunny, thanks for replying, it's much appreciated. And yes, I figured that tying `struct` into my interface definition was the way to go.

**Comment by ianstormtaylor** [comment]
Unfortunately there's no easy way to do this. Typically the runtime validations are going to be more strict than the compile-time validations anyways, so you'll want to use `Infer` to generate your types and save on repetition.

However, with `0.12.0` there's a new `Describe` type utility function that will help you ensure your structs match your types if you don't want to infer them:

```ts
type User = {
  id: number
  name: string
}

const User: Describe<User> = object({
  id: string(), // This mistake will fail to pass type checking!
  name: string(),
})
```

That will ensure they stay in sync, but it still requires some duplication.

Going further and auto-generating structs from the TypeScript types themselves would require some compiler-side logic, and would not be useful in lots of cases where you want to further refine the runtime types. It's likely not something that the Superstruct will support.

**Comment by thesunny** [comment]
Woe! That's such a cool idea! Love it!

**Comment by mattfysh** [comment]
There is `ts-to-zod` which does this for generating zod schemas from typescript types. Maybe there is a way to fork this project and modify just the part that generates zod code, to make it produce superstruct types instead?
