### ISSUE TITLE
[Question] When to use CustomTypes vs Refinements

### ISSUE THREAD

**Issue by d-gubert** [ianstormtaylor/superstruct#555]
Hi! It's not clear for me whether I need to use a refinement or a custom type in my application.

In the docs, there are examples that kinda overlap conceptually, like:

```
import { define } from 'superstruct'
import isEmail from 'is-email'
import isUuid from 'is-uuid'

const Email = define('Email', isEmail)
const Uuid = define('Uuid', (value) => isUuid.v4(value))
```
[docs](https://docs.superstructjs.org/api-reference/types#custom-types)

```
import { number, refine } from 'superstruct'

const PositiveInteger = refine(number(), 'PositiveInteger', (value) => {
  return Number.isInteger(value) && value >= 0
})
```
[docs](https://docs.superstructjs.org/api-reference/refinements#custom-refinements)

But it looks like I could make an `email` custom refinement (which was actually my first thought) to achieve the same functionality. Same goes for making a `PositiveInteger` custom type.

Is there an underlying feature that differentiates both approaches? What should I consider when trying to decide whether to go with one or the other?

**Comment by ianstormtaylor** [comment]
Hey @d-gubert good question. They definitely overlap, so you can implement them either way. With simple things like `email` is probably doesn't matter much which you choose. The benefit of refinements is that when defining your custom validation logic, the input value has already been validated to a specific type instead of `unknown`. For simple strings this doesn't save much, but when refining validation for more complex types it can be helpful.
