### ISSUE TITLE
Comparsion with io-ts

### ISSUE THREAD

**Issue by dodas** [ianstormtaylor/superstruct#582]
Hey there!

I wonder how `superstruct` compares to `io-ts`. I couldn't find any info about that.
@ianstormtaylor Can you provide any insight , please?

Thanks!

**Comment by ianstormtaylor** [comment]
Hey @dodas, good question. I took inspiration from `io-ts` when writing some parts of `superstruct`. As for how they compare, I can't really give an unbiased take, but I can give you a super high level view…

In terms of features they are very similar, although the naming of certain things might be different. I honestly don't know the full extent of `io-ts`'s "encoding" and "decoding" concepts. `superstruct` has easier to understand implementations of these for pieces like "nullability" or for "coercion" of input values, but they might not apply to the same use cases.

In terms of feel though, they are very different. `io-ts` is heavily invested in "functional programming", which you'll notice right away in its docs. If you use `fp-ts` or `ramda` already it's likely a better fit. Whereas `superstruct` is "functional" but only in design, it doesn't require any functional programming knowledge to use. It's likely much easier to use for the majority of people in the JavaScript/TypeScript ecosystem.

In terms of bundle size, I'm not sure. But I can say that `superstruct` beats most other libraries in this aspect, and I've tried to keep it around ~3kb since release. It's hard for me to tell with `io-ts` because so often in its docs it requires other libraries like `fp-ts` or nested packages like `io-ts/Decoder`.

So yeah... I think it can be summed up as: if you read through the `io-ts` docs do you feel like you truly understand what's going on?

I'm not going to lie, I get functional programming, and reading through `io-ts`'s docs is still very tedious. I wouldn't ever choose it personally because getting other people ramped up on it would have a huge cost that I wouldn't want to impose on them.
