### ISSUE TITLE
Allow custom error messages for user defined types

### ISSUE THREAD

**Issue by istarkov** [ianstormtaylor/superstruct#60]
It seems like now is impossible to declare custom error messages for user types

What if in this example I want to provide 2 different error messages, one for first check  `The provided {value} is not email` and other for length check `Email can't be longer than 256 smbs`

```javascript
const struct = superstruct({
  types: {
    email: value => isEmail(value) && value.length < 256,
  }
})
```

May you allow to provide a message in validate function via `throw` or as a result? Or I just not found a solution.

**Comment by ianstormtaylor** [comment]
Hey @istarkov, I think I'd be open to this.

In general, I don't advise creating the messages themselves inside the validation function, since you aren't really able to guarantee who your audience is or what the specific use case is when defining them, since they can be used in any number of structs/situations. 

However, I think it does sound reasonable to be able to expose information in the validator to describe which aspect is invalid. For that, it seems reasonable to allow validators to return either `true`, `false` or a code string. For example:

```js
const struct = superstruct({
  types: {
    email: (value) => {
      if (!isEmail(value)) return 'invalid'
      if (value.length > 256) return 'too_long'
      return true
  }
})
```

This way in 90% of cases people can continue to just use `true/false`, but if they need to differentiate between specific validation cases they can opt to get more specific. I'd love a PR that implements this if you're down to try!

I think it should be exposed as `error.code`.

**Comment by istarkov** [comment]
Super! I'll try to provide implementation.
