### ISSUE TITLE
why use a functional interface, not fluent?

### ISSUE THREAD

**Issue by dko-slapdash** [ianstormtaylor/superstruct#621]
Hi.

Curious, why superstruct prefers functional style in many places and not [fluent style](https://en.wikipedia.org/wiki/Fluent_interface) (method chaining) as e.g. yup does? Fluent style is a well-known way to reduce complexity/boilerplate. E.g. compare:

```ts
// functional/nested style
const struct = refine(
  object({
    oldPassword: nonempty(string()),
    newPassword: refine(
      nonempty(string()),
      "is-long",
      ({ length }) =>
        length >= MIN_PASSWORD_LEN ||
        `Password is shorter than ${MIN_PASSWORD_LEN} characters`
    ),
    newPassword2: nonempty(string()),
  }),
  "match",
  ({ newPassword2, newPassword }) =>
    newPassword2 === newPassword || "Passwords do not match"
)
``` 

and

```ts
// fluent style
const st = object({
  oldPassword: string().refine(nonempty),
  newPassword: string()
    .refine(nonempty)
    .refine(
      "is-long",
      ({ length }) =>
        length >= MIN_PASSWORD_LEN ||
        `Password is shorter than ${MIN_PASSWORD_LEN} characters`
    ),
  newPassword2: string().refine(nonempty),
}).refine(
  "match",
  ({ newPassword2, newPassword }) =>
    newPassword2 === newPassword || "Passwords do not match"
);
```

The latter looks a little cleaner. (Assuming there is Struct.refine() method which accepts either a refinement function or a name+lambda custom validator.) Also, in fluent style, it's instantly visible that the refiners start executing from top to bottom, whilst in "aaa(bbb(ccc()))" style it's not clear, whether ccc is executed first or aaa.

P.S.
Heavily evaluating the library now for our ~100 structures, sorry for so many issues with questions/proposals created.

**Comment by ianstormtaylor** [comment]
Hey @dko-slapdash that's a good question.

I agree with you that fluent is slightly easier to read/write, although I'd also add the caveat that the two examples are pretty close to one another.

But the reason that Superstruct picked the functional approach is that it differs from most validation libraries in that it doesn't expect to (or try to) provide every single validation you will need for your codebase, just the most common ones. In my opinion, this is a mistake that other libraries make, which results in APIs where you're not exactly sure what is being tested for, and which results in huge large bundle sizes.

Instead, Superstruct makes writing custom validations easy. This is hard to do well with a fluent API.

To explain what I mean, I'll show you how I would personally re-write the example:

```ts
import { string, object, size, refine } from 'superstruct'

const matches = (Struct, key) => {
  return refine(Struct, 'matches', (value, context) => {
    const parent = context.branch[context.branch.length - 2]
    return value === key
  })
}

const Password = size(string(), 8, 256)
const PasswordForm = object({
  oldPassword: string(),
  newPassword: Password,
  newPasswordAgain: matches(Password, 'newPassword'),
})
```

I think this re-write is _much_ clearer than either of the initial two examples for someone trying to understand what exactly is being validated. Not only that, but it it allows you to re-use the `matches` helper in other places if need be, or open-source it if you wanted.

If you try to implement the same thing in a fluent API, you'll run into the issue that there is no `string().matches()` because Superstruct didn't ship with it. So now you have this awkward behavior where "core" logic gets special-cased and fluent-ized, whereas userland code is functional, making it even harder to read than if only one style was used.

Hope that makes sense.

The other benefit to functional is that you only bundle the structs you actually use with treeshaking.

**Comment by dko-slapdash** [comment]
Thanks for the detailed explanation and example!

> you'll run into the issue that there is no string().matches()

I actually didn't propose to add fluent API for everything, only for some very core things from the domain: Struct.refine(), Struct.coerce() (because they are 2 core building blocks) and Struct.nullable(), Struct.optional() (because they alter TS type of the result). Nothing more. There is really no need for any other fluent methods. (And you already have some helper methods in Struct, like Struct.create(), Struct.assert(), Struct.mask() which make tree shaking slightly less efficient.)

It's possible to even add just 1 helper method to Struct - `struct.apply(x, ...y)` - which just calls `x(struct, ...y)` and can work with all of the above. (Or Struct.chain() - similar to the `|>` operator some other languages have: https://docs.hhvm.com/hack/expressions-and-operators/pipe.)

Rephrasing your example, here is how it could've looked like with those 4 methods fluent:

```
import { string, object, size, refine } from 'superstruct'

function matches(Struct, key) {
  return refine(Struct, 'matches', (value, context) => {
    const parent = context.branch[context.branch.length - 2]
    return value === key // ? - but doesn't matter
  })
}

function passwordish(Struct) {
  return refine(Struct, 'passwordish', size(Struct, 8, 256));
}

const PasswordForm = object({
  oldPassword: string().apply(nonempty),
  newPassword: string().apply(passwordish),
  newPasswordAgain: string().apply(matches, 'newPassword')),
})
```

I.e. `struct.apply(x, y, z)` is just a sugar for `x(struct, y, z)`

The general idea is to turn x(y(z(a))) into something like `a |> z |> y |> x` (or `a.apply(z).apply(y).apply(x)` syntactically.

> I think this re-write is much clearer than either of the initial two examples

100% true. The only concern is that this approach is slightly more opinionated than the average engineers can ever grok/accept. I doubt people will adopt it easily (same applies to functional programming, regexes and other "hard" (C) (R) concepts). As opposed to that, fluent API helpers are easy to adopt. My belief is that yup and joi will be deflating over time, and the users will migrate to something new & modern (in terms of TS) - i.e. to your library.

**Comment by ianstormtaylor** [comment]
@dko-slapdash ah I see, sorry for assuming you meant fluent everything. You're right that there are some struct methods, but those are all for using the struct to validate a value, which is the inherent use case for a struct.

The problem is that `.apply()` method is just an arguable readability gain, and is more annoying to type. Since ES20XX will get the pipeline operator at some point, if always using fluent instead of functional is a particular sticking point then people can use Babel to get the fluent-like syntax across their entire codebase, instead of every library having to add code to accommodate it.
