### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by pyros2097** [ianstormtaylor/superstruct#80]
This seems a lot like this library https://github.com/icebob/fastest-validator.

How would you compare superstruct's performance vs fastest-validator?

**Comment by ianstormtaylor** [comment]
I’m not sure, but if you or anyone was interested in writing up some benchmarks that would be awesome!

**Comment by ianstormtaylor** [comment]
Going to close this out since it's not super actionable for this library itself. I'd love for an external party to write up benchmarks if they're interested. Although for things like REST APIs, it's very unlikely that the validation layer is going to be where the performance bottlenecks are (unless you have extremely large incoming data).
