### ISSUE TITLE
Error when bundle with webpack

### ISSUE THREAD

**Issue by forsigner** [ianstormtaylor/superstruct#83]
Unexpected token: name (StructError) [./node_modules/superstruct/lib/index.es.js:7,0][index.ef29450fbb2e4dc5d2e2.js:147554,6]

**Comment by doodlewind** [comment]
Are you using a dev build or a production one? In production, if you don't translate ES6 in `node_modules`, uglify plugin may throw such error since our bundle contains dependency in ES6 while this plugin can only transform ES5. If using ES6 in production is fine for you, using `uglify-es` can be a workaround.

**Comment by forsigner** [comment]
In my case, I use superstruct with `npm i superstruct -S`.

**Comment by doodlewind** [comment]
Possible same issue: https://github.com/webpack/webpack/issues/1542#issuecomment-308747244

@ianstormtaylor how about releasing `index.es.js` in ES5?

**Comment by ianstormtaylor** [comment]
@doodlewind open to the idea!

Is the issue just with the `import` syntax Babel transforms? I think it would make sense for us to not use `import` in this library, and change them to `require` for CJS support instead. What do you think? Or is it something else?

**Comment by jackmellis** [comment]
I'm having this issue too. I think the distributed files should be ES5 compatible (not just commonjs). Right now I have to write an awkward exclude regex in my webpack config to include superstruct in my babel parsing
