### ISSUE TITLE
Expected a value of type `undefined` for `author.test` but received `undefined`

### ISSUE THREAD

**Issue by saighost** [ianstormtaylor/superstruct#89]
```
'use strict';
const { struct } = require('../lib/superstruct/lib/index');
const Article = struct({
  id: 'number',
  author: {
    id: 'number',
  },
});
const data = {
  id: 34,
  author: {
    id: 1,
    test: undefined,
  },
};
const article = Article(data);
console.log('article', article);
```
I use the struct to validate data from excel, some unsed keys are set to undefined, and I get an error like :
Expected a value of type `undefined` for `author.test` but received `undefined`

I try to partial, but it is not recursive. so I create this issues and a pull request.

**Comment by szhangpitt** [comment]
I think it could also be a matter of the error message... e.g. the message could be “didn’t expect a property ‘test’ but got ‘test: undefined’” ... instead of the current one. 

Having a property with value of undefined vs. not having this property at all is two concept; how this module treat them is a design decision we can then discuss.

**Comment by saighost** [comment]
Undefined is not a null.
This is a data validator, so I care about the value when the key in the schema. And it validates the type of value.
This issue wants to ignore keys these not in the schema and with an undefined value. The only difference is these keys is enumerable.

**Comment by szhangpitt** [comment]
If I understand it correctly, you would like your code in [first comment](https://github.com/ianstormtaylor/superstruct/issues/89#issue-295298067) to pass the check and not throw error?

Did you try this? (Seems to work on 0.5.0)

```js
const {struct} = require('superstruct');

const Article = struct({
  id: 'number',
  author: struct.partial({      // use struct.partial at this level
    id: 'number',
  }),
});
const data = {
  id: 34,
  author: {
    id: 1,
    test: undefined,
  },
};

const article = Article(data);
console.log('article', article);
```

**Comment by szhangpitt** [comment]
You suggested to make `struct.partial()` recursive; I think that's a totally valid request. However I think it will change the essential behavior of `struct.partial()` (I know it's not 1.0.0 yet, but still..) 

My understanding for this library is that, object based schema is defined as explicit as possible, and any unexpected key (enumerable as you mentioned) will raise an error; that's more of a design decision. Another feature of this library is being highly compose-able, so that on each level, you can pass in a `struct` object to do more refined validation. 

To make `struct.partial()` recursive, I'm afraid it's somewhat going into opposite direction of compose-ability. 

This is only my opinion; apologize if I understood your intention incorrectly; and I'd love @ianstormtaylor  's insight.

**Comment by saighost** [comment]
#90 here is my pull request. There are two ways in it.
I had thought of adding an option to solve this problem, but then I saw `struct.partial()` in another issue, so I tried to solve this problem with `struct.partial()`.
I need to validate hundreds of columns in N sheets and filter some redundant columns, so I suggested here in mine opinion. Several ways to solve my problem, but I guess there is a convenient way to fix it.

**Comment by szhangpitt** [comment]
> I had thought of adding an option to solve this problem, but then I saw struct.partial() in another issue, so I tried to solve this problem with struct.partial().
> I need to validate hundreds of columns in N sheets and filter some redundant columns, so I suggested here in mine opinion. Several ways to solve my problem, but I guess there is a convenient way to fix it.

Got it. Would it be possible to then define a new method like `.recursivePartial()` for this new behavior? Because there might be other people would still want just one level of "partial" validation. We probably don't want adding a feature and meanwhile taking away another feature?

**Comment by saighost** [comment]
Follow his heart, `partial` is still not in the document, anything could happen.

**Comment by szhangpitt** [comment]
fair enough

**Comment by ianstormtaylor** [comment]
@szhangpitt that's a very good point, I hadn't considered that.

@saighost I think given @szhangpitt's comment, he's actually right that we shouldn't change the logic to be recursive because it does change the meaning of the structs. It does seem like usually you'll want `partial` to be referring only to the top-level properties, and not implying that the shape of any and all nested properties can be changed.

In which case, I'm sorry for not having caught that sooner.

**Comment by saighost** [comment]
Can make undefined value to pass without error？

**Comment by ianstormtaylor** [comment]
@saighost doesn't `struct.partial` fill that use case?

**Comment by saighost** [comment]
ok, maybe I replace `struct` `struct.partial` in recursive.

**Comment by ianstormtaylor** [comment]
@saighost awesome, let us know if you find any issues. Thank you for taking the time to write up that PR either way!

**Comment by saighost** [comment]
I will open another issue...
