### ISSUE TITLE
Nested errors dont report properly

### ISSUE THREAD

**Issue by pbarbiero** [ianstormtaylor/superstruct#96]
Say I have a schema like this:

```javascript
const schema = struct({
	readings: struct.optional(
		struct.list({
			date: 'number',
		}),
	),
});
```

If I pass it something like this:
```javascript
{ readings: [{ date: 'abc' }] }
```

I get this ambiguous error:
```
TypeError: Expected a value of type `[{date}] | undefined` for `readings` but received `[{"date":"abc"}]`.
```

I would expect an error something like this:
```
TypeError: Expected a value of type `number` for `readings.0.date` but received `string`.
```

As it stands now, its difficult to tell whats actually wrong.

**Comment by pbarbiero** [comment]
Hi @ianstormtaylor I've attempted to try to solve this myself but haven't been able to figure out an elegant way. Any chance you could take a look at this?

**Comment by adrianlocurcio** [comment]
Hi @ianstormtaylor  I think that many people will be grateful if the library has this feature. Do you plan to add at some point or no yet ?
Thanks

**Comment by ianstormtaylor** [comment]
I'm unsure how to handle this one. I'd be open to ideas.

For `intersection` structs, it makes sense for the nested errors to be shown. But for `union` structs it's less clear. Because an error in one of the structs in the union doesn't necessarily apply if the another struct in the union was the "closer" matched one.

We don't really know which one the data is attempt to pass?

We could potentially try and guess with the new `path` and `branch` properties. Taking the deepest-most path? Unsure. If someone wants to try to come up with a good way of doing it I'm all ears!

**Comment by fengzilong** [comment]
@ianstormtaylor how about let user make the decision

```js
const schema = struct( {
  options: struct.dynamic( function( rawData ) {
    if ( typeof rawData === 'undefined' ) {
      return struct.optional()
    }

    if ( rawData && rawData.key1 ) {
      return struct( { key1: 'string' } )
    }

    return struct( { key2: 'boolean' } )
  } )
} )
```
