### ISSUE TITLE
Serializing Structs

### ISSUE THREAD

**Issue by ccorcos** [ianstormtaylor/superstruct#961]
Hey there, I built [something similar](https://github.com/ccorcos/data-type-ts) a couple years ago, but I'd love to consolidate and use this superstruct.

The only feature missing is an ability to serialize and deserialize schemas. I want end-users to be able to define these schemas, not just programmers, so I need to be able to save the schemas in a database (e.g. localStorage) so that when the app reloads, users can use and modify those schemas.

Any thoughts on how to do this?

**Comment by ianstormtaylor** [comment]
Hey @ccorcos, thanks for asking again. I'm open to the logic for serializing structs being included. I'm assuming this would be to JSONSchema?

Ideally it would be done in a way that doesn't bloat the main library, since most use cases don't need it. Not sure how this would work exactly.

What did you have in mind?
